### ISSUE TITLE
how to run app.py

### ISSUE THREAD

**Issue by Trigger-broom-289** [dickreuter/betfair_horse_racing#1]
Greetings,
I have installed all the required packages, then ran conda env create -f environment_linux.yml
I can't see how to run the app.py exactly.

also, mongo:
> db.copyDatabase("horse_racing","horse_racing","dickreuter.com","rj","rj","SCRAM-SHA-1" )
{
	"ok" : 0,
	"errmsg" : "unable to login { ok: 0.0, errmsg: \"Authentication failed.\", code: 18, codeName: \"AuthenticationFailed\" }"
}
> 
bye

thanks for the help.

**Comment by dickreuter** [comment]
The app is using docopt. So it can be run in accordance with the parameters in the docstring.

**Comment by saneera223** [comment]
Hi I get the same error message with Mongo DB
