### ISSUE TITLE
Mongo access?

### ISSUE THREAD

**Issue by Trigger-broom-289** [dickreuter/betfair_horse_racing#2]
Hello, 
thanks for replying to my other post,
about mongo:

db.copyDatabase("horse_racing","horse_racing","dickreuter.com","rj","rj","SCRAM-SHA-1" )
{
"ok" : 0,
"errmsg" : "unable to login { ok: 0.0, errmsg: "Authentication failed.", code: 18, codeName: "AuthenticationFailed" }"
}

Regards
Stephane

**Comment by dickreuter** [comment]
Database is currently not publilc and is only available to contributors
